### ISSUE TITLE
Question about licensing

### ISSUE THREAD

**Issue by AnEagleinYourMind** [TeNNoX-Mods/Bacteria-Mod#15]
Hello @tennox, I am interested in maintaining mods for older versions of Minecraft. I would like to maintain your mods, however there are no licenses associated with them. So, I am requesting if you may attach an open source license to your old projects just to clarify things.

Thanks,
AnEagleinYourMind

**Comment by tennox** [comment]
Sounds great!! :)
https://gitlab.com/tennox-mods/Bacteria/-/commit/9c8b948bcbc3fda9d4de1eca2c636af372d111f2

Works for you?

If you need any support, I'm available!

**Comment by AnEagleinYourMind** [comment]
Thank you so much! Can you place the key and lock mod under GPLv3 as well?

**Comment by tennox** [comment]
https://gitlab.com/tennox-mods/Key-And-Code-Lock/-/commit/4f97a7fbb75d2547f92fabcd314f21a38ac4f1ba

**Comment by tennox** [comment]
Can also give you commit access to gitlab if you send me your info and don't care about doing it in your own namespace

**Comment by AnEagleinYourMind** [comment]
Thanks, but I plan on just creating a fork. I appreciate the fast response!

**Comment by tennox** [comment]
Okay, keep me posted, then I can add links to the pages ;)
